<a href="https://colab.research.google.com/github/Nishant-8009/DL/blob/main/lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
t1 = torch.tensor(4.)
t1.shape

In [ ]:
t2 = torch.tensor([1,2.,3,5])

t2.shape

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

In [ ]:
y = w * x + b
y

In [ ]:
y.backward()

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

Lec 2 Linear Regression

In [ ]:
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.7055, -0.6217,  0.5275],
        [ 0.5770, -1.2273,  0.2831]], requires_grad=True)
tensor([ 0.8636, -0.6627], requires_grad=True)


In [ ]:
def model(x):
    return x @ w.t() + b

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

In [ ]:
# Compare with targets
print(targets)

In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
# Compute loss
loss = mse(preds, targets)
print(loss)

In [ ]:
loss.backward()

In [ ]:
print(w)
print(w.grad)

In [ ]:
print(b)
print(b.grad)

In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [ ]:
# Let's verify that the loss is actually lower
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

Train model

In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

In [ ]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

In [ ]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

In [ ]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    print(loss)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

tensor(2.0006, grad_fn=<DivBackward0>)
tensor(1.9855, grad_fn=<DivBackward0>)
tensor(1.9707, grad_fn=<DivBackward0>)
tensor(1.9560, grad_fn=<DivBackward0>)
tensor(1.9414, grad_fn=<DivBackward0>)
tensor(1.9271, grad_fn=<DivBackward0>)
tensor(1.9129, grad_fn=<DivBackward0>)
tensor(1.8990, grad_fn=<DivBackward0>)
tensor(1.8851, grad_fn=<DivBackward0>)
tensor(1.8715, grad_fn=<DivBackward0>)
tensor(1.8580, grad_fn=<DivBackward0>)
tensor(1.8447, grad_fn=<DivBackward0>)
tensor(1.8315, grad_fn=<DivBackward0>)
tensor(1.8185, grad_fn=<DivBackward0>)
tensor(1.8056, grad_fn=<DivBackward0>)
tensor(1.7929, grad_fn=<DivBackward0>)
tensor(1.7804, grad_fn=<DivBackward0>)
tensor(1.7680, grad_fn=<DivBackward0>)
tensor(1.7558, grad_fn=<DivBackward0>)
tensor(1.7437, grad_fn=<DivBackward0>)
tensor(1.7317, grad_fn=<DivBackward0>)
tensor(1.7199, grad_fn=<DivBackward0>)
tensor(1.7083, grad_fn=<DivBackward0>)
tensor(1.6968, grad_fn=<DivBackward0>)
tensor(1.6854, grad_fn=<DivBackward0>)
tensor(1.6742, grad_fn=<D

In [ ]:
preds

tensor([[ 57.4154,  70.4028],
        [ 82.7583, 100.7424],
        [117.0394, 132.6415],
        [ 21.7429,  38.2084],
        [102.6624, 118.4358]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [ 68.,  97.,  70.],
        [101.,  44.,  37.],
        [ 88., 134.,  59.],
        [ 91.,  88.,  64.]])
tensor([[ 56.,  70.],
        [102., 120.],
        [ 21.,  38.],
        [118., 132.],
        [ 81., 101.]])


In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5735,  0.2510, -0.2268],
        [-0.3716,  0.2546,  0.1006]], requires_grad=True)
Parameter containing:
tensor([-0.4546, -0.4877], requires_grad=True)


In [ ]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5735,  0.2510, -0.2268],
         [-0.3716,  0.2546,  0.1006]], requires_grad=True),
 Parameter containing:
 tensor([-0.4546, -0.4877], requires_grad=True)]

In [ ]:
# Import nn.functional
import torch.nn.functional as F

In [ ]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
fit(50, model, loss_fn, opt, train_dl)

Epoch [10/50], Loss: 26.3142
Epoch [20/50], Loss: 39.2359
Epoch [30/50], Loss: 30.5236
Epoch [40/50], Loss: 40.3584
Epoch [50/50], Loss: 31.3181


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.9323,  70.7870],
        [ 78.9953,  98.6016],
        [124.3696, 137.0480],
        [ 25.9222,  39.8994],
        [ 93.4465, 113.7496],
        [ 56.7013,  69.6912],
        [ 78.2148,  98.3038],
        [124.3452, 137.4475],
        [ 27.1532,  40.9952],
        [ 93.8970, 114.5476],
        [ 57.1518,  70.4891],
        [ 77.7643,  97.5058],
        [125.1501, 137.3459],
        [ 25.4717,  39.1014],
        [ 94.6775, 114.8454]], grad_fn=<AddmmBackward0>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])